GET https://mlailpkc-api-839a553f0085.herokuapp.com/api/logs
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|IcBpjJLjV9WQ5ECopEkbyMFwEdTEmPn3gD3c8Bm9

###
POST https://mlailpkc-api-839a553f0085.herokuapp.com/api/admin/auth/login
Content-Type: application/json
Accept: application/json

{
    "username": "admin@mlailpkc.mil.ng",
    "password": "admin@321"
}

###
GET https://mlailpkc-api-839a553f0085.herokuapp.com/api/student/registration/verify-email/c24eeea2-1664-4f05-ab23-6f9635845fed/jawadrumah@gmail.com
Accept: application/json
###
GET https://mlailpkc-api-839a553f0085.herokuapp.com/api/admin/student-registrations/list
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJqd3QtYXVkaWVuY2UiLCJpc3MiOiJtbGFpbHBrYy5taWwubmciLCJVU0VSX1VJRCI6IjJmNzNhNWMyLWM0M2ItNDZjNC1hZmIwLTYyMWM1ZmExYTQ1MyIsIlVTRVJfUEVSTUlTU0lPTlMiOltdLCJleHAiOjE3MTYzOTEzODd9.aBzCMuy0f_CNMNWwNcf7mM-FCBpcoEmW1kuqhslZT08

###
POST https://mlailpkc-api-839a553f0085.herokuapp.com/api/admin/student-registrations/process/78829949-5888-4182-8f58-b97ca1a4b651
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJqd3QtYXVkaWVuY2UiLCJpc3MiOiJtbGFpbHBrYy5taWwubmciLCJVU0VSX1VJRCI6IjJmNzNhNWMyLWM0M2ItNDZjNC1hZmIwLTYyMWM1ZmExYTQ1MyIsIlVTRVJfUEVSTUlTU0lPTlMiOltdLCJleHAiOjE3MTYzOTEzODd9.aBzCMuy0f_CNMNWwNcf7mM-FCBpcoEmW1kuqhslZT08

{
    "action": "APPROVED"
}

